---
application:
  api:
    swagger:
      path: /api-docs/swagger
      version: 3.22.0
      layout: StandaloneLayout
      deepLinking: true
      urls:
        - name: service-one
          url: http://localhost:8081/api-docs/swagger/service-one-0.1.yml
          apiUrl: http://localhost:8081/api/service-one
        - name: service-two
          url: http://localhost:8082/api-docs/swagger/service-two-0.1.yml
          apiUrl: http://localhost:8082/api/service-two
---
micronaut:
    application:
        name: swagger-multi-service
    server:
      port: 8080
    router:
      static-resources:
        swagger:
          paths: classpath:META-INF/swagger
          mapping: ${application.api.swagger.path}/**
---
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    url:
      enabled: true